version: "3"

networks:
  envidat:
    external: true

services:
  email_service:
    image: docker.io/jdrouet/catapulte:1.0.0-alpha-1-alpine
    container_name: email_relay_staging
    environment:
      TEMPLATE__TYPE: local
      TEMPLATE__PATH: /templates
    env_file:
      - runtime.env
    volumes:
      - $HOME/config/email-relay-staging/templates:/templates:ro
    ports:
      - 3010:3000
    networks:
      - envidat
    restart: unless-stopped
